# Generated by Django 3.0.6 on 2020-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200529_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('SALE', 'sale'), ('NEW', 'new'), ('PROMOTION', 'promotion')], max_length=9),
        ),
    ]
