# Generated by Django 3.0.6 on 2020-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200602_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
